DROP TABLE IF EXISTS "ZACCOUNT";
CREATE TABLE ZACCOUNT ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZUSER INTEGER, ZEMAIL VARCHAR );
INSERT INTO "ZACCOUNT" VALUES(1,1,1,1,'');
DROP TABLE IF EXISTS "ZLOCATION";
CREATE TABLE ZLOCATION ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZPROFILE INTEGER, Z5_PROFILE INTEGER, ZLONGITUDE FLOAT, ZLATITUDE FLOAT );
INSERT INTO "ZLOCATION" VALUES(1,2,1,1,6,-122.03,37.336);
DROP TABLE IF EXISTS "ZMESSAGE";
CREATE TABLE ZMESSAGE ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZUNREAD INTEGER, ZTIMESTAMP INTEGER, ZSENDER INTEGER, Z5_SENDER INTEGER, ZTEXT VARCHAR, ZCHANNEL VARCHAR );
DROP TABLE IF EXISTS "ZPICTURE";
CREATE TABLE ZPICTURE ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZPROFILE INTEGER, Z5_PROFILE INTEGER, ZPID VARCHAR, ZTHUMB BLOB );
DROP TABLE IF EXISTS "ZPROFILE";
CREATE TABLE ZPROFILE ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZFBID INTEGER, ZORDER INTEGER, ZONLINESTATUS INTEGER, ZLOCATION INTEGER, ZPICTURE INTEGER, ZWEIGHT INTEGER, ZSEX INTEGER, ZSHOWDISTANCE INTEGER, ZETHNICITY INTEGER, ZSHOWAGE INTEGER, ZHEIGHT INTEGER, ZLIKES INTEGER, ZACCOUNT INTEGER, ZLASTONLINE TIMESTAMP, ZUPDATED TIMESTAMP, ZBIRTHDAY TIMESTAMP, ZABOUT VARCHAR, ZHEADLINE VARCHAR, ZNAME VARCHAR, ZPHONE VARCHAR, ZOID VARCHAR, ZFBUSERNAME VARCHAR );
INSERT INTO "ZPROFILE" VALUES(1,6,1,0,0,1,1,NULL,NULL,NULL,1,NULL,0,NULL,NULL,1,0,0,NULL,'','','','','','');
-- UPDATE "ZPROFILE"
-- SET Z_ENT=6,
--     Z_OPT=1,
--     ZFBID=0,
--     ZORDER=0,
--     ZONLINESTATUS=1,
--     ZLOCATION=1,
--     ZPICTURE=NULL,
--     ZWEIGHT=NULL,
--     ZSEX=NULL,
--     ZSHOWDISTANCE=1,
--     ZLIKES=NULL,
--     ZHEIGHT=NULL,
--     ZACCOUNT=1,
--     ZLASTONLINE=0,
--     ZETHNICITY=NULL,
--     ZFBID=0,
--     ZUPDATED=0,
--     ZBIRTHDAY=NULL,
--     ZABOUT='',
--     ZHEADLINE='',
--     ZNAME='',
--     ZPHONE='',
--     ZOID='',
--     ZFBUSERNAME=''
-- WHERE Z_PK=1
DROP TABLE IF EXISTS "Z_3RECEIVERS";
CREATE TABLE Z_3RECEIVERS ( Z_3RECEIVEDMESSAGES INTEGER, Z_5RECEIVERS INTEGER, PRIMARY KEY (Z_3RECEIVEDMESSAGES, Z_5RECEIVERS) );
DROP TABLE IF EXISTS "Z_METADATA";
CREATE TABLE Z_METADATA (Z_VERSION INTEGER PRIMARY KEY, Z_UUID VARCHAR(255), Z_PLIST BLOB);
DROP TABLE IF EXISTS "Z_PRIMARYKEY";
CREATE TABLE Z_PRIMARYKEY (Z_ENT INTEGER PRIMARY KEY, Z_NAME VARCHAR, Z_SUPER INTEGER, Z_MAX INTEGER);
INSERT INTO "Z_PRIMARYKEY" VALUES(1,'Account',0,1);
INSERT INTO "Z_PRIMARYKEY" VALUES(2,'Location',0,1);
INSERT INTO "Z_PRIMARYKEY" VALUES(3,'Message',0,0);
INSERT INTO "Z_PRIMARYKEY" VALUES(4,'Picture',0,0);
INSERT INTO "Z_PRIMARYKEY" VALUES(5,'Profile',0,1);
INSERT INTO "Z_PRIMARYKEY" VALUES(6,'User',5,0);
CREATE INDEX ZACCOUNT_ZUSER_INDEX ON ZACCOUNT (ZUSER);
CREATE INDEX ZLOCATION_ZPROFILE_INDEX ON ZLOCATION (ZPROFILE);
CREATE INDEX ZMESSAGE_ZSENDER_INDEX ON ZMESSAGE (ZSENDER);
CREATE INDEX ZPICTURE_ZPID_INDEX ON ZPICTURE (ZPID);
CREATE INDEX ZPICTURE_ZPROFILE_INDEX ON ZPICTURE (ZPROFILE);
CREATE INDEX ZPROFILE_ZACCOUNT_INDEX ON ZPROFILE (ZACCOUNT);
CREATE INDEX ZPROFILE_ZLOCATION_INDEX ON ZPROFILE (ZLOCATION);
CREATE INDEX ZPROFILE_ZOID_INDEX ON ZPROFILE (ZOID);
CREATE INDEX ZPROFILE_ZPICTURE_INDEX ON ZPROFILE (ZPICTURE);
CREATE INDEX ZPROFILE_Z_ENT_INDEX ON ZPROFILE (Z_ENT);
